export const platforms = [
  "GitHub",
  "YouTube",
  "LinkedIn",
  "Twitter",
  "Twitch",
  "Facebook",
  "GitLab",
  "Hashnode",
  "CodePen",
  "freeCodeCamp",
  "Dev.to",
  "Codewars",
  "Stack Overflow",
];
export const platformColors: Record<string, string> = {
  GitHub: "#1a1a1a",
  YouTube: "#ee3939",
  LinkedIn: "#2d68ff",
  Twitter: "#1da1f2",
  Twitch: "#9146ff",
  Facebook: "#1877f2",
  GitLab: "#fc6d26",
  Hashnode: "#2962ff",
  CodePen: "#111",
  freeCodeCamp: "#302267",
  "Dev.to": "#111",
  Codewars: "#ad2c27",
  "Stack Overflow": "#f48024",
};
export const platformSymbols: Record<string, string> = {
  GitHub: "♟",
  YouTube: "▶",
  LinkedIn: "in",
  Twitter: "𝕏",
  Twitch: "◧",
  Facebook: "f",
  GitLab: "◇",
  Hashnode: "H",
  CodePen: "◈",
  freeCodeCamp: "⌁",
  "Dev.to": "DEV",
  Codewars: "⌘",
  "Stack Overflow": "▤",
};
